"""Initial migration 3

Revision ID: 160f73e4d721
Revises: 50a531a1a16b
Create Date: 2021-11-23 10:57:38.797473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160f73e4d721'
down_revision = '50a531a1a16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency', 'symbol',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency', 'symbol',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
