"""Initial migration 2

Revision ID: 50a531a1a16b
Revises: 2c89d1cbc660
Create Date: 2021-11-23 10:49:27.662613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a531a1a16b'
down_revision = '2c89d1cbc660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('minor_unit', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('country'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('currency_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_currency', sa.String(length=3), nullable=False),
    sa.Column('second_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_currency'),
    sa.UniqueConstraint('second_currency')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency_rates')
    op.drop_table('currency')
    # ### end Alembic commands ###
