"""Initial migration 4

Revision ID: 925df592f74e
Revises: 160f73e4d721
Create Date: 2021-11-23 10:59:11.527821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925df592f74e'
down_revision = '160f73e4d721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('currency_code_key', 'currency', type_='unique')
    op.drop_constraint('currency_name_key', 'currency', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('currency_name_key', 'currency', ['name'])
    op.create_unique_constraint('currency_code_key', 'currency', ['code'])
    # ### end Alembic commands ###
