"""Initial migration 6

Revision ID: d0ad5d46283f
Revises: 8529c6cd4667
Create Date: 2021-11-23 11:02:02.635356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ad5d46283f'
down_revision = '8529c6cd4667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('currency_country_key', 'currency', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('currency_country_key', 'currency', ['country'])
    # ### end Alembic commands ###
